name: Build Artifact
run-name: ${{ github.actor }} is building artifact

on: 
  workflow_dispatch:

jobs: 
  build_artifact: 
    env: # Or as an environment variable
      REACT_APP_SAMPLE_ENV: ${{ secrets.REACT_APP_SAMPLE_ENV }}
      REACT_APP_TEST_NON_SENSITIVE: ${{ vars.REACT_APP_TEST_NON_SENSITIVE }}

    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm ci

      - name: install sass
        run: npm install -g sass

      - name: compile css
        run: bash src/scss/runScss.bash

      - name: build
        run: npm run build
      
      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: poc-build-artifacts
          path: |
            build

        
